[package]
name = "okidoki"
version = "0.0.0"
edition = "2021"

[dependencies]
minifb = "0.24.0"
once_cell = "1.17.1"

[features]
default = []

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
