[package]
name = "okidoki"
version = "0.2.0"
edition = "2021"

[dependencies]
sdl2 = "0.35.2"
reqwest = "0.11.18"
ndarray = "0.15.0"

[features]
default = []

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
